[USER-PSA] PSADTO / PSAEntity(전 PSA) 분리 작업 완료
27kdt3team/team3 pull request #58
Opened 2024-12-07 07:33 UTC by duddnr0514

2024-12-07 07:45 UTC, 27kdt3team requested changes

2024-12-07 07:45 UTC, 27kdt3team commented on scvs/src/main/java/com/team3/scvs/service/PSAService.java
> +    private PSADTO convertToDTO(PSAEntity psaEntity) {
이 메서드가 Service에 있으면 안됩니다. 유틸쪽에 ConvertUtil이란게 있습니다. 거기에 넣어 주세요

2024-12-08 07:29 UTC, duddnr0514 commented
ConvertUtil로 유틸리티 메서드 이전 완료했습니다.

2024-12-10 00:20 UTC, 27kdt3team approved these changes

2024-12-10 00:25 UTC, merged